### ISSUE TITLE
Timestamp offsets

### ISSUE THREAD

**Issue by darrenscott** [jonathanadams/n3rgy-client#2]
I've been using your very useful library to obtain and visualise my smart meter data, but I am having issues with timestamps.

I note the **offsetConsumptionTimestamps** option provided to offset the timestamps by 30 minutes, and while I see this having an impact for consumption data, I naively assumed it would also impact tariff data too - but it doesn't. I guess the name of the option is accurate - it only affects consumption data!

However, I assume the same issue relating to the timestamp for each reported 30 minute period which affects consumption data also affects tariff data? Is there any reason why there is no equivalent option for tariff data? Is this just an oversight, or have I missed something?

**Comment by darrenscott** [comment]
I've actually just created a branch to add a new offsetTariffTimestamps option so that I can raise a pull request... but I am unable to push my branch due to permissions. How can I push my branch please?

**Comment by darrenscott** [comment]
OK - I've educated myself a bit more now! Pull request created.

**Comment by jonathanadams** [comment]
Thanks for submitting your pull request. 

When I wrote the library I had no need to offset my tariff data so likely why this was overlooked. You have found a need for this and it is likely that others will too.

I shall have a look at your pull request over the next week or so.

**Comment by darrenscott** [comment]
Thanks Jonathan

**Comment by darrenscott** [comment]
Hi @jonathanadams I just wondered if you'd had chance to review my pull request yet?

**Comment by jonathanadams** [comment]
> Hi @jonathanadams I just wondered if you'd had chance to review my pull request yet?

Apologies, I have not forgotten. Will merge soon and release soon!

**Comment by jonathanadams** [comment]
@darrenscott apologies this has taken so long. Merged and a new release should be up on NPM.
